# Generated by Django 2.0.5 on 2019-09-26 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_access', '0002_auto_20190503_0731'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
