# Generated by Django 2.1.7 on 2019-03-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('advisor', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('stage', models.CharField(max_length=50)),
            ],
        ),
    ]
