# Generated by Django 2.0.6 on 2019-04-02 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor_access', '0003_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
