# Generated by Django 2.0.6 on 2019-04-16 02:08

from django.db import migrations, models
import professor_access.models


class Migration(migrations.Migration):

    dependencies = [
        ('professor_access', '0005_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='project',
            name='details',
        ),
        migrations.AddField(
            model_name='project',
            name='background',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=professor_access.models.current_date),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
