# Generated by Django 2.0.6 on 2019-04-26 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor_access', '0009_auto_20190415_2336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='background',
            new_name='description',
        ),
    ]
