# Generated by Django 2.0.6 on 2019-04-26 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor_access', '0010_auto_20190426_0738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='instructor',
            new_name='student_name',
        ),
    ]
