# Generated by Django 2.0.6 on 2019-04-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor_access', '0012_remove_project_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='date',
        ),
        migrations.AddField(
            model_name='project',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
