# Generated by Django 2.0.6 on 2019-05-03 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor_access', '0014_project_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='photo',
            field=models.ImageField(blank=True, upload_to='upload'),
        ),
    ]
