# Generated by Django 2.0.6 on 2019-05-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor_access', '0015_project_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='student_name',
            field=models.CharField(max_length=50),
        ),
    ]
