# Generated by Django 2.0.6 on 2019-06-07 17:39

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('professor_access', '0018_examplemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='test',
            field=mdeditor.fields.MDTextField(default=1),
            preserve_default=False,
        ),
    ]
