# Generated by Django 2.0.6 on 2019-06-07 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor_access', '0019_project_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='test',
        ),
    ]
