# Generated by Django 2.0.6 on 2019-06-14 17:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor_access', '0020_remove_project_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExampleModel',
        ),
        migrations.RemoveField(
            model_name='project',
            name='photo',
        ),
        migrations.AlterField(
            model_name='project',
            name='note',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
