# Generated by Django 2.0.6 on 2019-06-21 02:52

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('professor_access', '0021_auto_20190614_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='note',
            field=tinymce.models.HTMLField(),
        ),
    ]
