# Generated by Django 2.0.6 on 2019-06-21 06:26

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor_access', '0022_auto_20190620_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='note',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
