# Generated by Django 2.0.6 on 2019-06-21 06:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor_access', '0023_auto_20190621_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='note',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
