# Generated by Django 2.0.6 on 2019-07-19 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor_access', '0024_auto_20190621_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
