# Generated by Django 2.0.5 on 2019-08-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor_access', '0029_auto_20190829_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='note',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='project2',
            name='description',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='project2',
            name='note',
            field=models.CharField(max_length=5000),
        ),
    ]
