# Generated by Django 2.0.5 on 2019-10-18 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor_access', '0033_auto_20191011_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='note',
        ),
    ]
