# Generated by Django 2.0.5 on 2019-10-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor_access', '0034_remove_project_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='note',
            field=models.CharField(default=1, max_length=5000),
            preserve_default=False,
        ),
    ]
