# Generated by Django 2.1.7 on 2019-02-21 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_access', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Stage',
            new_name='stage',
        ),
    ]
