# Generated by Django 2.0.5 on 2019-10-04 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='professor',
        ),
    ]
